version: "3"
services:
  nginx:
    image: nginx
    ports: 
      - 8080:8080
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
  passwordapi1:
    image: nicopaez/password-api
  passwordapi2:
    image: nicopaez/password-api